### ISSUE TITLE
Use available streams support functions in pipeline execution

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1777]
Stemming from #1690, Depends on #1703
The most direct way to fix this would probably be to update the storage adapter API so `getFile` returns a `ReadableStream` rather than a `Buffer`. Similarly, `putFile` should probably accept a `ReadableStream` for the file input (or perhaps adding support for a `ReadableStream` but not requiring it).
Taking a quick look at the codebase, the following files would need to be updated:
- [x] common/plugin/LocalExecutor.js
- [x] common/storage/index.js (#1703)
- [x] common/plugin/GeneratedFiles.js
- [x] plugins/UploadArtifact/UploadArtifact.js (Won't be necessary after #1717) 
- [x] common/storage/backends/StorageClient.js  (#1703)
- [x] plugins/GenerateJob/templates/run-debug.js
- [x] plugins/GenerateJob/templates/start.js
- [x] routers/InteractiveCompute/job-files/start-session.js
- [x] gme client  (#1703)
- [x] sciserver-files client (#1703)
- [x] s3 client (#1703)

_Originally posted by @brollb in https://github.com/deepforge-dev/deepforge/issues/1690#issuecomment-627370899_
